# Generated by Django 5.1.6 on 2025-10-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_contact_name_shipping_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
