# Generated by Django 5.1.6 on 2025-10-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shipping_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
