# Generated by Django 5.1.6 on 2025-10-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shipping_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['-default', '-selected', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='phone_code',
        ),
    ]
