# Generated by Django 5.1.6 on 2025-10-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_shipping_options_remove_shipping_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
