# Generated by Django 5.1.6 on 2025-10-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shipping_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionflutter',
            name='user',
        ),
    ]
