# Generated by Django 5.1.6 on 2025-10-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_transactionflutter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionflutter',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
