# Generated by Django 5.1.6 on 2025-10-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transactionflutter_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionflutter',
            name='link',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
