# Generated by Django 5.1.6 on 2025-10-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at']},
        ),
    ]
