name: Keep Render App Awake

on:
  schedule:
    # every 10 minutes (be a good citizen). You can try */5 for ~5 minutes.
    - cron: "*/10 * * * *"
  workflow_dispatch: {}  # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # avoid overlapping runs if one is delayed
    concurrency:
      group: keepalive
      cancel-in-progress: true

    steps:
      - name: Ping Render health endpoint
        env:
          URL: ${{ secrets.KEEPALIVE_URL }}
        run: |
          if [ -z "$URL" ]; then
            echo "KEEPALIVE_URL is not set"; exit 1
          fi

          # Optional jitter so all repos don’t hit on the exact same second
          sleep $((RANDOM % 30))

          echo "Pinging $URL"
          # --fail: exit non-zero on HTTP errors
          # --retry: tolerate transient network issues
          # --max-time: avoid hanging too long
          # --connect-timeout: quick fail on bad DNS/network
          curl --silent --show-error --fail \
               --retry 3 --retry-delay 5 \
               --max-time 15 --connect-timeout 5 \
               -A "render-keepalive-github-action" \
               "$URL"

          echo "OK ✅"
